services:
  - type: web
    name: finance-portfolio-app
    env: python
    buildCommand: pip install -r Finance_web/requirements.txt
    startCommand: gunicorn Finance_web.finance_web:app
    envVars:
      - key: FLASK_ENV
        value: development

